# **Binary Encoding**

In [16]:
import pandas as pd
import category_encoders as ce

In [13]:
data ={'Categories' : ['classA','classD','classB','classD','classC','classD','classC','classD','classA','classB','classA','classD','classC','classD']}
df = pd.DataFrame(data)
df

   Categories
0      classA
1      classD
2      classB
3      classD
4      classC
5      classD
6      classC
7      classD
8      classA
9      classB
10     classA
11     classD
12     classC
13     classD

In [14]:
bencoder = ce.BinaryEncoder(cols= ['Categories'], return_df= True)

In [15]:
df_binary_ecoded = bencoder.fit_transform(df)
df_binary_ecoded

    Categories_0  Categories_1  Categories_2
0              0             0             1
1              0             1             0
2              0             1             1
3              0             1             0
4              1             0             0
5              0             1             0
6              1             0             0
7              0             1             0
8              0             0             1
9              0             1             1
10             0             0             1
11             0             1             0
12             1             0             0
13             0             1             0