# **One-Hot Encoding**

In [3]:
import pandas as pd

In [5]:
data ={'Categories' : ['classA','classD','classB','classD','classC','classD','classC','classD','classA','classB','classA','classD','classC','classD']}
df = pd.DataFrame(data)
df

   Categories
0      classA
1      classD
2      classB
3      classD
4      classC
5      classD
6      classC
7      classD
8      classA
9      classB
10     classA
11     classD
12     classC
13     classD

In [6]:
onehotencodedvar = pd.get_dummies(df, columns=["Categories"])
onehotencodedvar

    Categories_classA  Categories_classB  Categories_classC  Categories_classD
0                True              False              False              False
1               False              False              False               True
2               False               True              False              False
3               False              False              False               True
4               False              False               True              False
5               False              False              False               True
6               False              False               True              False
7               False              False              False               True
8                True              False              False              False
9               False               True              False              False
10               True              False              False              False
11              False              False              False               True
12              False              False               True              False
13              False              False              False               True

In [7]:
onehotencodedvar = pd.get_dummies(df, columns=["Categories"], prefix='Dummy',drop_first= True)
onehotencodedvar

    Dummy_classB  Dummy_classC  Dummy_classD
0          False         False         False
1          False         False          True
2           True         False         False
3          False         False          True
4          False          True         False
5          False         False          True
6          False          True         False
7          False         False          True
8          False         False         False
9           True         False         False
10         False         False         False
11         False         False          True
12         False          True         False
13         False         False          True